const FETCH_ALL = "FETCH_ALL";

const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
const CREATE = "CREATE";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const LIKE = "LIKE";
const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";
const FETCH_POST = "FETCH_POST";
const COMMENT = "COMMENT";

export {
  FETCH_ALL,
  LIKE,
  CREATE,
  UPDATE,
  DELETE,
  AUTH,
  LOGOUT,
  FETCH_BY_SEARCH,
  START_LOADING,
  END_LOADING,
  FETCH_POST,
  COMMENT,
};
